# Generated by Django 5.2.4 on 2025-08-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('años_experiencia', models.PositiveIntegerField(default=22)),
                ('estudiantes_graduados', models.PositiveIntegerField(default=3500)),
                ('programas_academicos', models.PositiveIntegerField(default=15)),
                ('docentes_expertos', models.PositiveIntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
            },
        ),
    ]
