# Generated by Django 5.2.4 on 2025-08-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_seccion', models.CharField(default='¿Tienes dudas?', max_length=200)),
                ('descripcion_seccion', models.TextField(default='Aquí encontrarás respuestas a las preguntas más comunes sobre nuestros programas educativos y procesos de inscripción.')),
                ('whatsapp', models.CharField(default='+593989985431', max_length=50)),
                ('email', models.EmailField(default='info@ckmalau.edu.co', max_length=254)),
            ],
            options={
                'verbose_name': 'Configuración de FAQ',
                'verbose_name_plural': 'Configuración de FAQ',
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden'],
            },
        ),
    ]
