# Generated by Django 5.2.4 on 2025-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0003_remove_curso_rating_alter_beneficiocurso_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionProfesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nuestros Profesores', max_length=100)),
                ('descripcion', models.TextField(default='Conoce a nuestro equipo de profesionales altamente calificados que te guiarán en tu formación académica.')),
            ],
            options={
                'verbose_name': 'Configuración de Página de Profesores',
                'verbose_name_plural': 'Configuración de Página de Profesores',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_completo', models.CharField(blank=True, max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.URLField(blank=True, null=True)),
                ('color', models.CharField(choices=[('bg-blue-500', 'Azul'), ('bg-red-500', 'Rojo'), ('bg-green-500', 'Verde'), ('bg-yellow-500', 'Amarillo'), ('bg-indigo-500', 'Índigo'), ('bg-purple-500', 'Morado'), ('bg-pink-500', 'Rosa'), ('bg-gray-500', 'Gris')], default='bg-blue-500', max_length=20)),
                ('experiencia_años', models.PositiveIntegerField(default=0)),
                ('cursos_dictados', models.ManyToManyField(blank=True, related_name='profesores', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre', 'apellido'],
            },
        ),
    ]
