# Generated by Django 5.2.4 on 2025-08-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_predeterminado', models.TextField(default='Hola, me interesa obtener información sobre los cursos de CKMALAU')),
                ('ubicacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ubicacion')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuración WhatsApp',
            },
        ),
    ]
