# Generated by Django 5.2.4 on 2025-08-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_seccion', models.CharField(default='UNA EDUCACIÓN ENFOCADA EN TU ÉXITO', max_length=200)),
                ('subtitulo_seccion', models.TextField(default='Te brindamos las herramientas y el apoyo que necesitas para alcanzar tus metas profesionales.')),
                ('beneficio1_titulo', models.CharField(default='Docentes Capacitados', max_length=100)),
                ('beneficio1_descripcion', models.TextField(default='Personal docente altamente calificado.')),
                ('beneficio2_titulo', models.CharField(default='Materiales Gratuitos', max_length=100)),
                ('beneficio2_descripcion', models.TextField(default='Incluimos todos los materiales sin costo adicional.')),
                ('beneficio3_titulo', models.CharField(default='Formación Práctica', max_length=100)),
                ('beneficio3_descripcion', models.TextField(default='Programas actualizados y orientados al desarrollo profesional.')),
                ('beneficio4_titulo', models.CharField(default='Rápida Inserción Laboral', max_length=100)),
                ('beneficio4_descripcion', models.TextField(default='Te preparamos para integrarte de forma inmediata al campo laboral.')),
            ],
            options={
                'verbose_name': 'Beneficios',
                'verbose_name_plural': 'Beneficios',
            },
        ),
    ]
