# Generated by Django 5.2.4 on 2025-08-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='¡Inscríbete hoy y transforma tu futuro!', max_length=200)),
                ('descripcion', models.TextField(default='No dejes pasar la oportunidad de capacitarte con los mejores. Contáctanos por WhatsApp o visita nuestras instalaciones y da el primer paso hacia una carrera exitosa.')),
                ('whatsapp', models.CharField(default='+593989985431', max_length=20)),
            ],
            options={
                'verbose_name': 'Call To Action',
                'verbose_name_plural': 'Call To Action',
            },
        ),
    ]
