# Generated by Django 5.2.4 on 2025-08-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='ubicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ubicacion'),
        ),
    ]
