# Generated by Django 5.2.4 on 2025-08-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Más de 22 años formando profesionales con excelencia', max_length=200)),
                ('descripcion_principal', models.TextField(default='Somos una institución educativa comprometida con la formación integral de profesionales competentes...')),
                ('mision_titulo', models.CharField(default='Nuestra Misión', max_length=100)),
                ('mision_descripcion', models.TextField(default='Formar profesionales íntegros y competentes...')),
                ('vision_titulo', models.CharField(default='Nuestra Visión', max_length=100)),
                ('vision_descripcion', models.TextField(default='Ser reconocidos como la institución educativa líder...')),
                ('años_experiencia', models.PositiveIntegerField(default=22)),
            ],
            options={
                'verbose_name': 'Información Institucional',
                'verbose_name_plural': 'Información Institucional',
            },
        ),
    ]
