# Generated by Django 5.2.4 on 2025-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_seccion', models.CharField(default='Nuestros Estudiantes en Acción', max_length=200)),
                ('descripcion_seccion', models.TextField(default='Descubre el ambiente de aprendizaje dinámico y las experiencias prácticas que viven nuestros estudiantes día a día.')),
            ],
            options={
                'verbose_name': 'Configuración de Galería',
                'verbose_name_plural': 'Configuración de Galería',
            },
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('destacada', models.BooleanField(default=False, help_text='Mostrar en carrusel principal')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de Imágenes',
                'ordering': ['orden'],
            },
        ),
    ]
