# Generated by Django 5.2.4 on 2025-08-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriaimagen',
            name='imagen',
        ),
        migrations.AddField(
            model_name='galeriaimagen',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
