# Generated by Django 5.2.4 on 2025-08-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(help_text='Imagen de fondo para la sección principal', upload_to='hero/')),
                ('badge_text', models.CharField(default='Fundación Educativa', help_text='Texto que aparece en la insignia superior', max_length=100)),
                ('title', models.CharField(default='CKMALAU', help_text='Título principal', max_length=100)),
                ('subtitle', models.CharField(default='Transformando vidas a través de la educación', help_text='Subtítulo debajo del título principal', max_length=200)),
                ('description', models.TextField(default='Formamos profesionales competentes con valores sólidos para contribuir al desarrollo de nuestra sociedad', help_text='Descripción detallada')),
            ],
            options={
                'verbose_name': 'Sección Principal',
                'verbose_name_plural': 'Sección Principal',
            },
        ),
    ]
