# Generated by Django 5.2.4 on 2025-08-05 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_seccion', models.CharField(default='Programas de Formación', max_length=200)),
                ('descripcion_seccion', models.TextField(default='Descubre nuestros programas educativos diseñados para brindarte las habilidades y conocimientos necesarios para destacar en tu campo profesional.')),
                ('texto_badge', models.CharField(default='Nuestros Cursos', max_length=50)),
                ('color_badge_fondo', models.CharField(default='bg-purple-100', max_length=50)),
                ('color_badge_texto', models.CharField(default='text-purple-800', max_length=50)),
            ],
            options={
                'verbose_name': 'Configuración de Cursos',
                'verbose_name_plural': 'Configuración de Cursos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion', models.CharField(max_length=50)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDA', 'Híbrida')], default='PRESENCIAL', max_length=20)),
                ('certificacion', models.CharField(max_length=100)),
                ('color', models.CharField(default='bg-blue-500', max_length=50)),
                ('icono_url', models.URLField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('estudiantes', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='BeneficioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Beneficio del Curso',
                'verbose_name_plural': 'Beneficios del Curso',
            },
        ),
        migrations.CreateModel(
            name='ModuloCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Módulo del Curso',
                'verbose_name_plural': 'Módulos del Curso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Objetivo del Curso',
                'verbose_name_plural': 'Objetivos del Curso',
            },
        ),
        migrations.CreateModel(
            name='RequisitoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Requisito del Curso',
                'verbose_name_plural': 'Requisitos del Curso',
            },
        ),
        migrations.CreateModel(
            name='TemaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='cursos.modulocurso')),
            ],
            options={
                'verbose_name': 'Tema del Módulo',
                'verbose_name_plural': 'Temas del Módulo',
            },
        ),
    ]
