# Generated by Django 5.2.4 on 2025-08-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncursos',
            name='color_badge_fondo',
        ),
        migrations.RemoveField(
            model_name='configuracioncursos',
            name='color_badge_texto',
        ),
        migrations.RemoveField(
            model_name='configuracioncursos',
            name='texto_badge',
        ),
    ]
