# Generated by Django 5.2.4 on 2025-08-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_configuracioncursos_color_badge_fondo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='rating',
        ),
        migrations.AlterField(
            model_name='beneficiocurso',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='curso',
            name='color',
            field=models.CharField(choices=[('bg-blue-500', 'Azul'), ('bg-red-500', 'Rojo'), ('bg-green-500', 'Verde'), ('bg-yellow-500', 'Amarillo'), ('bg-indigo-500', 'Indigo'), ('bg-purple-500', 'Morado'), ('bg-pink-500', 'Rosa'), ('bg-gray-500', 'Gris')], default='bg-blue-500', max_length=50),
        ),
        migrations.AlterField(
            model_name='objetivocurso',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='requisitocurso',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='temamodulo',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
